### ISSUE TITLE
Paladin saving throws

### ISSUE THREAD

**Issue by Mitschy** [mivalsten/ddb-dm-screen#12]
Paladins "Aura of Protection" doesn't work properly.
I tryed a += on lines 129-135, but that doesnt work either since the value is still missing a value equal to (profiency modifier - 2) -> on a lvl 6 Paladin its off by 1, on a lvl 10 by 2 and so on.

![image](https://user-images.githubusercontent.com/23060223/61280528-50a01400-a7b8-11e9-814f-f8618e0e8bdb.png)

![image](https://user-images.githubusercontent.com/23060223/61280545-5ac21280-a7b8-11e9-982a-1f7fa0f88505.png)

**Comment by mivalsten** [comment]
While there is an error in the calculation (forgot about the cha mod or minimum of +1), I can't reproduce your error as it calculates those fine for me. Can you please upload your character's JSON file? You can access it by adding "/json" to the end of your character. First paste it to https://jsoneditoronline.org/ and remove all top nodes except "character".
![image](https://user-images.githubusercontent.com/8068803/61281895-afff2380-a7ba-11e9-91a1-5bd00a71a11c.png)

**Comment by Mitschy** [comment]
https://jsoneditoronline.org/?id=14734065eca540829ac607fb57fb964d
this should be it, good look.

**Comment by mivalsten** [comment]
I can't find anything wrong with the script or the data. Could you check if you are using latest version? It should be 1.2.4.

**Comment by Mitschy** [comment]
It's 1.2.4 and I updated it again, but it's still not working properly

**Comment by Mitschy** [comment]
an idea: what did you use to get those ability scores ? the base value for charisma ist 15 and +3 from the ability score improvements from lvl 4 and 8. the script is not considering this and just adds the bonus from the base score (15 -> +2) thats why there is 2 missing, or 1 with another paladin i tryed.

Edit: i used the standard array + ability score improvements to give +1 to my strength und +3 to my charisma score

**Comment by mivalsten** [comment]
Oh, wait, this can be indeed a race condition. I think I have an idea for a fix.

**Comment by mivalsten** [comment]
Ok, I was able to reproduce the error and fix that. Please verify.

**Comment by Mitschy** [comment]
verified, works now.
