### ISSUE TITLE
top character links not accessible

### ISSUE THREAD

**Issue by ubergrog** [mivalsten/ddb-dm-screen#24]
HI. Excellent work, appreciate you sharing!

One issue I've found is that the View, Edit, etc, links for the top character(s) are badly offset from the icons, after hunting around they do seem to be there but the URL's don't show up at the bottom so it's impossible to tell whether you're selecting the View or Delete (a bit of a difference :D). Resizing the browser shows that this only affects the top row, the second &amp; ensuing are fine.

Working on a Chromebook Version 75.0.3770.144 (Official Build) (64-bit) if that helps.

![image](https://user-images.githubusercontent.com/2738152/63113262-c2a27f00-bf57-11e9-9776-f54675b0d690.png)

**Comment by lothsun** [comment]
I can't seem to reproduce what you are describing. The screenshot you provided seem to show everything looks the same. Can you give me more information about your environment and browser?

Browser resolution, version, etc would help.

**Comment by ubergrog** [comment]
Hi.

I was just getting ready for a session tonight & managed to figure it out
that it has to do with the resolution I'm using. When the text size is too
big then the top links "disappear", but I can make them good by decreasing
the size of the window (ctrl-) far enough. My eyesite isn't that great
anymore but it's not so bad.

TX

-- 
GROG!

**Comment by lothsun** [comment]
I'm working on version 3.0 which will come with new styling for the script. Hopefully this will help with your link offsetting. I'm hoping to have it done by the end of this month to push out to everyone.

**Comment by ubergrog** [comment]
Much appreciated!

-- 
GROG!
