### ISSUE TITLE
Firefox not showing stats

### ISSUE THREAD

**Issue by octavian1213** [mivalsten/ddb-dm-screen#28]
I have the script and it is saying that it is running on the dndbeyond page through tampermonkey. but it is not showing the dm screen page.

**Comment by mivalsten** [comment]
H Octavian,
1. Awesome that someone still uses this!
2. looks like something has changed in a structure od a character sheet, I'll try to work out a fix in upcoming days. I'm amazed that it worked for almost a year.

**Comment by octavian1213** [comment]
Yes I love it one pane of glass and can see basic info of pc’s. 


Sent from Yahoo Mail for iPhone


On Wednesday, April 29, 2020, 6:41 PM, mivalsten <notifications@github.com> wrote:




H Octavian,
   
   - Awesome that someone still uses this!
   - looks like something has changed in a structure od a character sheet, I'll try to work out a fix in upcoming days. I'm amazed that it worked for almost a year.

**Comment by mivalsten** [comment]
Hi again,
I've commited a fix, please update the script and check if everything works for you. Also, looks like ddb is overhauling their character sheet as a lot of css classes are being renamed slightly (enough to break my script), so unfortunately expect that some things will not work properly (but it looks like they changed most of the things already).

Regards,
Greg

**Comment by Amunak** [comment]
I'm not the original reporter, but I have FF79 (dev edition) and use [ViolentMonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) for userscripts and it works perfectly. (Thank you.)
