### ISSUE TITLE
Armor Class incorrect

### ISSUE THREAD

**Issue by toddgrx** [mivalsten/ddb-dm-screen#33]
I'm using DM screen in DDB and while most of the PCs AC are correct, I have a player who's goliath shows AC 16 on screen, but click into character sheet from DM screen and it shows AC 14
![Screen Shot 2020-12-23 at 3 39 52 PM](https://user-images.githubusercontent.com/76538079/103038878-2cac3a80-4535-11eb-814f-9fe4ad83c210.png)
![Screen Shot 2020-12-23 at 3 40 50 PM](https://user-images.githubusercontent.com/76538079/103038930-4cdbf980-4535-11eb-8c72-f16d293ea827.png)

**Comment by mivalsten** [comment]
hi @toddgrx
Please use this DM screen instead, it's working much faster than mine.
https://github.com/TeaWithLucas/DNDBeyond-DM-Screen

Happy holidays and lots of nat 20s in upcoming 2021. :)
