### ISSUE TITLE
Saving throw values don't consider all modifiers

### ISSUE THREAD

**Issue by Mitschy** [mivalsten/ddb-dm-screen#6]
Hi, 
it's a great tool just something that i noticed on a paladin in my campaign.
It doens't include custom modifiers and the paladins Aura of Protection (Level 6 paladin class feature) to the saving throw value.
![image](https://user-images.githubusercontent.com/23060223/61211414-d01ddc80-a6ff-11e9-9140-e709eac21482.png)
![image](https://user-images.githubusercontent.com/23060223/61211452-e5930680-a6ff-11e9-9d7a-1756538da89a.png)

**Comment by mivalsten** [comment]
Fix for paladin in newest commit.
