### ISSUE TITLE
Draconic Resilience not counted in max HP

### ISSUE THREAD

**Issue by MathieuDR** [mivalsten/ddb-dm-screen#7]
A draconic sourcerer max HP isn't counted in the MAX HP

![image](https://user-images.githubusercontent.com/1561671/61214011-0579f880-a707-11e9-889e-64b18a17fd8a.png)

![image](https://user-images.githubusercontent.com/1561671/61214016-0c087000-a707-11e9-917d-15093809c28e.png)

![image](https://user-images.githubusercontent.com/1561671/61214049-23475d80-a707-11e9-9c01-48afa419bc99.png)

**Comment by mivalsten** [comment]
This one is tricky as it requires to track sorcerer levels and such, but I think I can make this work somehow. And it must be different from otions like dwarven fortitude which grants HP per character level not class level. Ugh. Thanks for pointing this out.

**Comment by mivalsten** [comment]
Workaround applied in version 1.2.3.
