### ISSUE TITLE
HP not displaying correctly 

### ISSUE THREAD

**Issue by sfpies** [mivalsten/ddb-dm-screen#8]
Two of my characters are showing total hp incorrectly. One is -4 hp and one is -10 hp

**Comment by mivalsten** [comment]
@sfpies Please post json data from your character link with "/json" added at the end. After copying it paste it to https://jsoneditoronline.org/ and remove all nodes except "character".

**Comment by sfpies** [comment]
Wont let me upload json files so converted it to text. Hope that works for you. This is the one with -4 hp
[document.txt](https://github.com/mivalsten/ddb-dm-screen/files/3393030/document.txt)

**Comment by sfpies** [comment]
This is the character with -10 hp
[document.txt](https://github.com/mivalsten/ddb-dm-screen/files/3393092/document.txt)

**Comment by mivalsten** [comment]
Fixed in version 1.2.3
Character with -10 HP had bonus hitPoint which were not handled at all, is fixed now.
Character with -4 had draconic bloodline which is fixed in a very hacky way, but should be calculated properly now.

**Comment by sfpies** [comment]
Thanks.
